#!/usr/bin/env bash

main() {
    echo ".Commands" > docs/modules/ROOT/nav-commands.adoc
    mapfile arr < <(java -jar build/libs/spring-cli-0.0.1-SNAPSHOT.jar help)
    for path in "${arr[@]}"; do
        IFS=':' read -ra FIELDS <<< "$path"
        echo ${FIELDS[0]}
        for F in "${FIELDS[@]:1}"; do
            NAME="${F// /-}"
            # echo $NAME
            java -jar build/libs/spring-cli-0.0.1-SNAPSHOT.jar help $F > docs/modules/ROOT/pages/commands/$NAME.adoc
            echo "** xref:commands/$NAME.adoc[$F]" >> docs/modules/ROOT/nav-commands.adoc
        done
        # echo ${FIELDS[@]:1}
    done
}

main
