name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: macos
            os: macos-latest
          - nickname: linux
            os: ubuntu-latest
          - nickname: windows
            os: windows-latest
    name: CI Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - run: ./gradlew build --no-daemon
      # - uses: actions/upload-artifact@v3
      #   with:
      #     path: build/libs/*.jar
      #     retention-days: 1
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: buildreports-${{ matrix.nickname }}
          path: build/reports
          retention-days: 1
