name: e2e

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: test
        run: |
          wget https://github.com/jreleaser/jreleaser/releases/download/v1.8.0/jreleaser-native-1.8.0-osx-x86_64.zip
          unzip jreleaser-native-1.8.0-osx-x86_64.zip
          ls
          find jreleaser-standalone-1.8.0-osx-x86_64
  # e2e:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - nickname: macos
  #           os: macos-latest
  #           graal: 22.3.1
  #         - nickname: linux
  #           os: ubuntu-latest
  #           graal: 22.3.1
  #         - nickname: windows
  #           os: custom-large-windows-2022
  #           graal: 22.3.1
  #   name: E2E ${{ matrix.nickname }}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: adopt
  #         java-version: 17
  #         cache: gradle
  #     - uses: graalvm/setup-graalvm@v1
  #       with:
  #         version: ${{ matrix.graal }}
  #         java-version: 17
  #         components: native-image
  #         set-java-home: false
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - run: |
  #         ./gradlew clean build nativeBuild
  #     - name: run e2e tests
  #       working-directory: e2e/spring-cli-e2e-tests
  #       run: |
  #         npm install
  #         npm run build-spring-shell-e2e
  #         npm test
  #     - name: Publish Test Results
  #       uses: EnricoMi/publish-unit-test-result-action/composite@v1
  #       if: always()
  #       with:
  #         files: e2e/spring-cli-e2e-tests/junit.xml
