name: JR Build

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle
      - name: Gradle Build
        run: ./gradlew build -x test --no-daemon -PcliRelease=true
      - name: Completion Files
        run: |
          mkdir -p build/completion/bash
          java -jar build/libs/spring-cli-${{ inputs.version }}.jar completion bash > build/completion/bash/spring
      - uses: actions/upload-artifact@v3
        with:
          name: fatjar
          path: build/libs/*.jar
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: completion
          path: build/completion
          retention-days: 1
