name: GA

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version like, 1.0.0, 1.0.0-RC1, etc'
        required: true

jobs:

  precheck:
    uses: ./.github/workflows/jr-version.yml
    with:
      version: ${{ github.event.inputs.version }}
  build:
    needs: [precheck]
    uses: ./.github/workflows/jr-build.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  javaarchive:
    needs: [precheck,build]
    uses: ./.github/workflows/jr-assemble-javaarchive.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  jlink:
    needs: [precheck,build]
    uses: ./.github/workflows/jr-assemble-jlink.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  jpackage:
    needs: [precheck,jlink]
    uses: ./.github/workflows/jr-assemble-jpackage.yml
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}
  release:
    needs: [precheck,javaarchive,jpackage]
    uses: ./.github/workflows/jr-release.yml
    secrets: inherit
    with:
      ref: ${{ needs.precheck.outputs.ref }}
      version: ${{ needs.precheck.outputs.version }}

