name: JR Release

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - uses: actions/create-github-app-token@v1
        id: cli-repo-token
        with:
          app-id: ${{ vars.SPRING_CLI_BOT_APP_ID }}
          private-key: ${{ secrets.SPRING_CLI_BOT_APP_PRIVATE_KEY }}
          owner: ${{ vars.SPRING_CLI_REPO_TOKEN_OWNER }}
          repositories: ${{ vars.SPRING_CLI_REPO_TOKEN_REPOSITORIES }}
      - uses: actions/create-github-app-token@v1
        id: cli-org-token
        with:
          app-id: ${{ vars.SPRING_CLI_BOT_APP_ID }}
          private-key: ${{ secrets.SPRING_CLI_BOT_APP_PRIVATE_KEY }}
          owner: ${{ vars.SPRING_CLI_ORG_TOKEN_OWNER }}
          repositories: ${{ vars.SPRING_CLI_ORG_TOKEN_REPOSITORIES }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Download fatjar
        uses: actions/download-artifact@v3
        with:
          name: fatjar
          path: build/libs

      - name: Download javaarchive
        uses: actions/download-artifact@v3
        with:
          name: javaarchive
          path: out/jreleaser/assemble/spring-cli/java-archive

      - name: Download jpackage
        uses: actions/download-artifact@v3
        with:
          name: jpackage
          path: out/jreleaser/assemble/spring-cli-installer/jpackage

      - name: Download jlink
        uses: actions/download-artifact@v3
        with:
          name: jlink
          path: out/jreleaser/assemble/spring-cli-standalone/jlink

      - name: Release
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: -c ${{ vars.SPRING_CLI_JRELEASER_CONFIG }} full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ steps.cli-repo-token.outputs.token }}
          JRELEASER_HOMEBREW_GITHUB_TOKEN: ${{ steps.cli-org-token.outputs.token }}
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}

      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
